### PR TITLE
fitter development

### PR DESCRIPTION
**Pull request by kmtsui**
Major changes
- Optimization of make sequence
- Addition of `WCSIM_TreeConvert` app to directly read WCSIM output. Requires WCSIM installation and is only turned on when `WCSIMDIR` environment variable is set
- New functions in `Chisq` class to define multiple fit paramaters
-- Add cathode (optical) parameters which work as spline evaluated from TH3D
- Addition of `TestFitter` to app to fit all PMTs in the detector
-- Needs output files from `WCSIM_TreeConvert` which stores photon hits of each PMT
-- "Reference map" is just the prediction from "nominal" MC simulation (will need more sophisticated way to get the reference and make prediction)
-- Use toml config file to declare fit parameters

### CODE REVIEW

**Comment by Acraplet** [comment]
Hi Ka Ming, thank you for all of this work, it looks like great progress. 
I am not yet managing to compile your code either with WCSIMDIR or without. I am having different errors which I think I linked to root versions for the main part, but still unsure. 

Issue 1: when trying to compile without WCSIMDIR the TestFitter.cc code still asked for the WCSimRootEvent.hh and other WCSim headers that we do not have except if copying them over from WCSim into mPMTmapping/lib, which isn't the most efficient.

Issue 2: still when trying to compile without WCSIMDIR, after having added the necessary headers to mPMTmapping/lib I am having the following errors: `../include/toml/toml_helper.h:141:11: error: redefinition of default argument for ‘class T’
  141 | template <typename T = toml::value, typename Key = std::string>
      |           ^~~~~~~~
../include/toml/toml_helper.h:88:11: note: original definition appeared here
   88 | template <typename T = toml::value, typename Key = std::string>
` 
This is something I have seen before when trying to use toml with my version of root (6.26). I wonder if it is a compatibility issue. When adding my WCSIMDIR (or WCSIMDIR/include) directly to the LD_LIBRARY_PATH the compiler doesn't find the headers. 

Issue 3: when trying to compile with WCSim (and therefore with another version of root, namely 5.34). Then the compiler  fails on members of std: `error: ‘unique_ptr’ is not a member of ‘std’` , `error: ‘map’ in namespace ‘std’ does not name a type
`

I wanted to ask what version of root you are using (is it the same for your WCSim install and the wc_calibration code?), so I can check whether that is my issue. In the meantime I will try a couple more things and also chat with Lauren towards the end of the week about how best to use the container in this case and whether this could solve my issues. 

If you have any inputs it would be greatly appreciated, and I guess, if you have time maybe add a couple of lines about how to run WCSimTreeConvert, what the output looks like and how that then feeds into the Fitter code. I have made a new branch kmtsui-main for testing so you can make your PR to this branch.

**Comment by kmtsui** [comment]
> Issue 1: when trying to compile without WCSIMDIR the TestFitter.cc code still asked for the WCSimRootEvent.hh and other WCSim headers that we do not have except if copying them over from WCSim into mPMTmapping/lib, which isn't the most efficient.

Funny I didn't see this behavior. Did you do a make clean first?

**Comment by kmtsui** [comment]
> Issue 2: still when trying to compile without WCSIMDIR, after having added the necessary headers to mPMTmapping/lib I am having the following errors

I didn't see such error when I tested on root5 and root6.22. `toml` should just be a light weight include that is not coupled to root. But if have another root installation please try to see the compile results. Just remember to do a make clean, and also if you use the WCSim library you will need to use the same root that compiles WCSIM.

**Comment by kmtsui** [comment]
> Issue 3: when trying to compile with WCSim (and therefore with another version of root, namely 5.34). Then the compiler fails on members of std: error: ‘unique_ptr’ is not a member of ‘std’ , error: ‘map’ in namespace ‘std’ does not name a type 

Just fixed the issue in the new commit

**Comment by kmtsui** [comment]
Just tested the compilation in a clean ROOT 6.26/10 container (https://github.com/root-project/root-docker) and I don't see those errors... Looks like maybe there are environment/setup conflicts on your side.

**Comment by Acraplet** [comment]
Hi again. When I DO NOT have  WCSIMDIR set:

I can now compile with root 5.34. And with root 6.24/08, in both cases with the `-std=c++11` flag. 

I also tried with a new root 6.26/10 install but there I still get the toml_helper error. In that case am compiling by default with `-std=c++17` (could that be the issue? trying to enforce std=c++11 brute-forcely). I haven't tried the container root install that you linked but I can try that next.

**Comment by Acraplet** [comment]
When I DO have WCSIMDIR I can compile but I need to do `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR/include` instead of `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR`. 

I will start testing/reading through your update but I have some hardware on my plate this week too so it might take a while. I'll keep you posted here.

**Comment by kmtsui** [comment]
> I also tried with a new root 6.26/10 install but there I still get the toml_helper error. In that case am compiling by default with -std=c++17 (could that be the issue? trying to enforce std=c++11 brute-forcely). 

The ROOT container is using c++17 and there is no error... Maybe there are some conflicts when you set up other environments

**Comment by kmtsui** [comment]
> When I DO have WCSIMDIR I can compile but I need to do export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR/include instead of export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR.

The library directory should already be given explicitly in the compile statement. Unless somehow you have some necessary libraries inside $WCSIMDIR/include?

**Comment by Acraplet** [comment]
> > When I DO have WCSIMDIR I can compile but I need to do export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR/include instead of export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR.
> 
> The library directory should already be given explicitly in the compile statement. Unless somehow you have some necessary libraries inside $WCSIMDIR/include?

I do have the necessary WCSim headers in $WCSIMDIR/include (e.g. WCSimDetectorConstruction.hh, evNtuple.h, etc... like in the official [repo](https://github.com/WCTE/WCSim/tree/nuPRISM/develop/include)) I actually also need to run `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR` for having libWCSimRoot.so but the WCSimTreeConvert code runs.

**Comment by Acraplet** [comment]
Could you please push an example spline for your cathode fit? Which code did you use to produce this reference file?  I would like to try the fitter with that and have a look at the file structure to see how best to re-arrange my abwff/rayff reference files. 

I do not think that we should use global maps as reference for mPMT-level effects, here are my gut feelings on why: 
1. large degeneracies between local and global effects
2. larger/longer reference simulation 

that is not a problem for now but at some point I might send you or run myself some WCSim config files to run (basically mPMT scans like the 'hedgehog' I have been looking at) to compare with the 'general map' approach. 

I see that you take each PMT as its own bin, I think that we can be finer than that using also the incoming phi and theta angle that WCSimTreeConvert calculates, like what I showed on Thursday. The same method can be used to split into timing bins. I will have a look into that, it shouldn't be difficult and then I can write the bit that looks up for each mPMT the correct bin from my hedgehog simulations.

**Comment by kmtsui** [comment]
> I do have the necessary WCSim headers in $WCSIMDIR/include (e.g. WCSimDetectorConstruction.hh, evNtuple.h, etc... like in the official [repo](https://github.com/WCTE/WCSim/tree/nuPRISM/develop/include)) I actually also need to run LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR for having libWCSimRoot.so but the WCSimTreeConvert code runs.

The headers are needed for compilation but should already be handled with `-I$(WCSIMDIR)/include` in the Makefile.

Can you give me the full commands and terminal output from starting the shell to compilation? I need also your start-up settings in e.g. ~/.bashrc

**Comment by kmtsui** [comment]
> Could you please push an example spline for your cathode fit? Which code did you use to produce this reference file? I would like to try the fitter with that and have a look at the file structure to see how best to re-arrange my abwff/rayff reference files.

Those inputs are just for testing and I don't intend to use them in actual analysis. In the end we will use the same inputs (reference map)s to predict the number of hits in each PMT

**Comment by kmtsui** [comment]
> I see that you take each PMT as its own bin, I think that we can be finer than that using also the incoming phi and theta angle that WCSimTreeConvert calculates, like what I showed on Thursday.

The data format is intended for the data fit where we don't know exactly where photons hit the mPMTs. For reference map generation we should definitely use fine enough binning.

**Comment by Acraplet** [comment]
> > I do have the necessary WCSim headers in $WCSIMDIR/include (e.g. WCSimDetectorConstruction.hh, evNtuple.h, etc... like in the official [repo](https://github.com/WCTE/WCSim/tree/nuPRISM/develop/include)) I actually also need to run LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WCSIMDIR for having libWCSimRoot.so but the WCSimTreeConvert code runs.
> 
> The headers are needed for compilation but should already be handled with `-I$(WCSIMDIR)/include` in the Makefile.
> 
> Can you give me the full commands and terminal output from starting the shell to compilation? I need also your start-up settings in e.g. ~/.bashrc

My bad, I defined WCSIMDIR in relative path and not absolute, fixing that resolved the problem. Sorry that was a dumb mistake.
